src/postix/backoffice/urls.py
from django.conf.urls import url

from . import views

app_name = 'backoffice'
urlpatterns = [
    url('^login/$', views.LoginView.as_view(), name='login'),
    url('^logout/$', views.logout_view, name='logout'),
    url('^switch-user/$', views.switch_user, name='switch-user'),

    url('^create_user/$', views.create_user_view, name='create-user'),
    url('^users/reset_password/(?P<pk>[0-9]+)/$', views.ResetPasswordView.as_view(), name='reset-password'),
    url('^users/$', views.UserListView.as_view(), name='user-list'),

    url('^session/new/$', views.new_session, name='new-session'),
    url('^session/(?P<pk>[0-9]+)/end/$', views.end_session, name='end-session'),
    url('^session/(?P<pk>[0-9]+)/report/$', views.session_report, name='session-report'),
    url('^session/(?P<pk>[0-9]+)/resupply/$', views.resupply_session, name='resupply-session'),
    url('^session/(?P<pk>[0-9]+)/move/$', views.move_session, name='move-session'),
    url('^session/(?P<pk>[0-9]+)/reverse/$', views.reverse_session_view, name='reverse-session'),
    url('^session/(?P<pk>[0-9]+)/$', views.SessionDetailView.as_view(), name='session-detail'),
    url('^session/$', views.SessionListView.as_view(), name='session-list'),
    url('^reports/$', views.ReportListView.as_view(), name='report-list'),

    url('^records/$', views.RecordListView.as_view(), name='record-list'),
    url('^records/new/$', views.RecordCreateView.as_view(), name='new-record'),
    url('^records/(?P<pk>[0-9]+)/$', views.RecordDetailView.as_view(), name='record-detail'),
    url('^records/(?P<pk>[0-9]+)/print/$', views.record_print, name='record-print'),
    url('^records/entity/$', views.RecordEntityListView.as_view(), name='record-entity-list'),
    url('^records/entity/new/$', views.RecordEntityCreateView.as_view(), name='new-record-entity'),
    url('^records/entity/(?P<pk>[0-9]+)/$', views.RecordEntityDetailView.as_view(), name='record-entity-detail'),
    url('^records/entity/(?P<pk>[0-9]+)/delete/$', views.RecordEntityDeleteView.as_view(), name='record-entity-delete'),

    # These are called 'wizard' cause they're only for wizards (erm, superusers)
    url('^wizard/users/$', views.WizardUsersView.as_view(), name='wizard-users'),
    url('^wizard/settings/$', views.WizardSettingsView.as_view(), name='wizard-settings'),
    url('^wizard/cashdesks/$', views.WizardCashdesksView.as_view(), name='wizard-cashdesks'),
    url('^wizard/import/$', views.WizardPretixImportView.as_view(), name='wizard-import'),
    url('^wizard/items/$', views.WizardItemListView.as_view(), name='wizard-items-list'),
    url('^wizard/items/new$', views.WizardItemCreateView.as_view(), name='wizard-items-create'),
    url('^wizard/items/(?P<pk>[0-9]+)/$', views.WizardItemEditView.as_view(), name='wizard-items-edit'),

    url('^$', views.MainView.as_view(), name='main'),
]

src/postix/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

admin.autodiscover()

js_info_dict = {
    'packages': (),
}

urlpatterns = [
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('postix.api.urls', namespace='api')),
    url(r'^backoffice/', include('postix.backoffice.urls', namespace='backoffice')),
    url(r'^troubleshooter/', include('postix.troubleshooter.urls', namespace='troubleshooter')),
    url(r'', include('postix.desk.urls', namespace='desk')),
]

src/postix/backoffice/views/record.py
from django.contrib.auth import get_user_model
from django.core.files.storage import default_storage
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import (
    CreateView, DeleteView, ListView, TemplateView, UpdateView,
)

from postix.backoffice.forms.record import (
    RecordCreateForm, RecordEntityForm, RecordUpdateForm,
)
from postix.backoffice.report import generate_record
from postix.core.models import CashdeskSession, Record, RecordEntity

from .utils import (
    BackofficeUserRequiredMixin, SuperuserRequiredMixin,
    backoffice_user_required,
)

User = get_user_model()


class RecordListView(BackofficeUserRequiredMixin, TemplateView):
    model = Record
    template_name = 'backoffice/record_list.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        records = Record.objects.all()
        sessions = CashdeskSession.objects.filter(end__isnull=False)
        running_total = 0
        all_objects = sorted(list(records) + list(sessions), key=lambda element: getattr(element, 'datetime', (getattr(element, 'end', None))))
        for obj in all_objects:
            if isinstance(obj, CashdeskSession):
                amount = obj.get_cash_transaction_total()
                obj.amount = amount
                running_total += obj.amount
            elif obj.type == 'incoming':
                running_total += obj.amount
            else:
                running_total -= obj.amount
            obj.running_total = running_total
        ctx['records'] = all_objects
        return ctx


class RecordCreateView(BackofficeUserRequiredMixin, CreateView):
    model = Record
    form_class = RecordCreateForm
    template_name = 'backoffice/new_record.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['backoffice_users'] = User.objects.filter(is_backoffice_user=True)
        ctx['carriers'] = set(Record.objects.all().values_list('carrier', flat=True))
        return ctx

    def get_success_url(self):
        return reverse('backoffice:record-print', kwargs={'pk': self.get_form().instance.pk})


class RecordDetailView(BackofficeUserRequiredMixin, UpdateView):
    model = Record
    form_class = RecordUpdateForm
    template_name = 'backoffice/record_detail.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['backoffice_users'] = User.objects.filter(is_backoffice_user=True)
        ctx['carriers'] = set(Record.objects.all().values_list('carrier', flat=True))
        return ctx

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        kwargs['editable'] = 'edit' in self.request.GET
        return kwargs

    def get_success_url(self):
        return reverse('backoffice:record-print', kwargs={'pk': self.kwargs['pk']})


@backoffice_user_required
def record_print(request, pk: int):
    record = get_object_or_404(Record, pk=pk)
    record_path = record.get_record_path()

    if not record_path or 'cached' not in request.GET:  # TODO: don't regenerate pdf always
        record_path = generate_record(record)

    response = HttpResponse(content=default_storage.open(record_path, 'rb'))
    response['Content-Type'] = 'application/pdf'
    response['Content-Disposition'] = 'inline; filename=record-{}.pdf'.format(record.pk)
    return response


class RecordEntityListView(SuperuserRequiredMixin, ListView):
    model = RecordEntity
    template_name = 'backoffice/record_entity_list.html'
    context_object_name = 'entities'


class RecordEntityCreateView(SuperuserRequiredMixin, CreateView):
    model = RecordEntity
    form_class = RecordEntityForm
    template_name = 'backoffice/new_record_entity.html'

    def get_success_url(self):
        return reverse('backoffice:record-entity-list')


class RecordEntityDetailView(SuperuserRequiredMixin, UpdateView):
    model = RecordEntity
    form_class = RecordEntityForm
    template_name = 'backoffice/new_record_entity.html'

    def get_success_url(self):
        return reverse('backoffice:record-entity-list')


class RecordEntityDeleteView(SuperuserRequiredMixin, DeleteView):
    model = RecordEntity
    template_name = 'backoffice/delete_record_entity.html'
    context_object_name = 'record'

    def get_success_url(self):
        return reverse('backoffice:record-entity-list')

src/postix/backoffice/views/user_management.py
from typing import Union

from django.contrib import messages
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import ugettext as _
from django.views.generic import FormView, ListView

from ...core.models import User
from ..forms import CreateUserForm, ResetPasswordForm, get_normal_user_form
from .utils import BackofficeUserRequiredMixin, backoffice_user_required


@backoffice_user_required
def main_view(request: HttpRequest) -> HttpResponse:
    return render(request, 'backoffice/main.html')


@backoffice_user_required
def create_user_view(request: HttpRequest) -> Union[HttpResponseRedirect, HttpResponse]:
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(**form.cleaned_data)
            if user.is_backoffice_user:
                messages.success(request, _('Backoffice user {user} has been created.').format(user=user.username))
            else:
                messages.success(request, _('User {user} has been created.').format(user=user.username))
            return redirect('backoffice:create-user')
    else:
        form = get_normal_user_form()

    return render(request, 'backoffice/create_user.html', {'form': form})


class UserListView(BackofficeUserRequiredMixin, ListView):
    template_name = 'backoffice/user_list.html'
    queryset = User.objects.all().order_by('username')


class ResetPasswordView(BackofficeUserRequiredMixin, FormView):
    form_class = ResetPasswordForm
    template_name = 'backoffice/reset_password.html'

    def get_context_data(self):
        pk = self.kwargs['pk']
        ctx = super().get_context_data()
        ctx['user'] = User.objects.get(pk=pk)
        return ctx

    def post(self, request, pk):
        form = self.get_form()
        pk = self.kwargs['pk']
        user = User.objects.get(pk=pk)
        if user.is_superuser and not request.user.is_superuser:
            messages.error(self.request, _('You can only change administrator passwords if you are an admin yourself.'))
            return self.form_valid(form)

        if form.is_valid():
            user.set_password(form.cleaned_data.get('password1'))
            user.save()
            messages.success(self.request, _('Passwort has been changed.'))
            return self.form_valid(form)

    def get_success_url(self):
        return reverse('backoffice:user-list')

src/postix/backoffice/views/utils.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin

from postix.core.models import User


def is_backoffice_user(user: User) -> bool:
    if user.is_authenticated:
        return user.is_superuser or user.is_backoffice_user
    return False


class BackofficeUserRequiredMixin(UserPassesTestMixin):
    login_url = 'backoffice:login'

    def test_func(self) -> bool:
        return is_backoffice_user(self.request.user)


backoffice_user_required = user_passes_test(is_backoffice_user, login_url='backoffice:login')


def is_superuser(user: User) -> bool:
    if user.is_authenticated:
        return user.is_superuser
    return False


class SuperuserRequiredMixin(UserPassesTestMixin):
    login_url = 'backoffice:login'

    def test_func(self) -> bool:
        return is_superuser(self.request.user)


superuser_required = user_passes_test(is_superuser, login_url='backoffice:login')

src/postix/backoffice/views/wizard.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import ugettext as _
from django.views.generic import FormView, ListView, TemplateView, UpdateView

from postix.backoffice.forms import (
    CashdeskForm, EventSettingsForm, ImportForm, ItemForm,
)
from postix.backoffice.views.utils import SuperuserRequiredMixin
from postix.core.models import EventSettings, Item, User


class WizardSettingsView(SuperuserRequiredMixin, FormView):
    template_name = 'backoffice/wizard_settings.html'
    form_class = EventSettingsForm

    def post(self, request):
        form = self.get_form()
        if form.is_valid():
            form.save()
            messages.success(request, _('The settings have been updated \o/'))
            return self.form_valid(form)

    def get_initial(self):
        settings = EventSettings.get_solo()
        attrs = {
            attr: getattr(settings, attr)
            for attr in EventSettingsForm().fields
        }
        attrs.update({'initialized': True})
        return attrs

    def get_success_url(self):
        return reverse('backoffice:wizard-settings')


class WizardCashdesksView(SuperuserRequiredMixin, FormView):
    template_name = 'backoffice/wizard_cashdesks.html'
    form_class = CashdeskForm

    def post(self, request):
        form = self.get_form()
        if form.is_valid():
            form.save()
            messages.success(request, _('The cashdesk has been created \o/'))
            return self.form_valid(form)

    def get_initial(self):
        settings = EventSettings.get_solo()
        attrs = {
            attr: getattr(settings, attr)
            for attr in EventSettingsForm().fields
        }
        attrs.update({'initialized': True})
        return attrs

    def get_success_url(self):
        return reverse('backoffice:wizard-cashdesks')


class WizardUsersView(SuperuserRequiredMixin, TemplateView):
    template_name = 'backoffice/wizard_users.html'

    def get_context_data(self):
        ctx = super().get_context_data()
        ctx['users'] = User.objects.order_by('username')
        return ctx

    def post(self, request):
        target = request.POST.get('target')
        pk = request.POST.get('user')
        user = User.objects.get(pk=pk)

        if 'troubleshooter' in target:
            user.is_troubleshooter = target[-1] == 'y'
        elif 'backoffice' in target:
            user.is_backoffice_user = target[-1] == 'y'
        elif 'superuser' in target:
            user.is_superuser = target[-1] == 'y'
        user.save()

        if target[-1] == 'y':
            messages.success(request, _('User rights have been expanded'))
        else:
            messages.success(request, _('User rights have been curtailed.'))
        return redirect('backoffice:wizard-users')


class WizardPretixImportView(SuperuserRequiredMixin, FormView):
    template_name = 'backoffice/wizard_import.html'
    form_class = ImportForm

    def post(self, request):
        form = self.get_form()
        if form.is_valid():
            from postix.core.utils.pretix_import import import_pretix_data
            try:
                pretix_import = request.FILES['_file']
                import_pretix_data(
                    pretix_import.read().decode(),
                    add_cashdesks=form.cleaned_data['cashdesks'],
                    questions=form.cleaned_data['questions'],
                )
                messages.success(request, _('The import has been processed \\o/'))
            except Exception as e:
                messages.error(request, _('The import could not be processed: ') + str(e))
            return self.form_valid(form)

    def get_initial(self):
        settings = EventSettings.get_solo()
        attrs = {
            attr: getattr(settings, attr)
            for attr in EventSettingsForm().fields
        }
        attrs.update({'initialized': True})
        return attrs

    def get_success_url(self):
        return reverse('backoffice:wizard-import')


class WizardItemListView(SuperuserRequiredMixin, ListView):
    template_name = 'backoffice/wizard_item_list.html'
    model = Item


class WizardItemCreateView(SuperuserRequiredMixin, FormView):
    template_name = 'backoffice/wizard_item_edit.html'
    form_class = ItemForm

    def post(self, request):
        form = self.get_form()
        if form.is_valid():
            form.save()
            messages.success(request, _('The item has been saved \o/'))
            return self.form_valid(form)

    def get_success_url(self):
        return reverse('backoffice:wizard-items-list')


class WizardItemEditView(SuperuserRequiredMixin, UpdateView):
    template_name = 'backoffice/wizard_item_edit.html'
    model = Item
    form_class = ItemForm

    def form_valid(self, form):
        form.save()
        messages.success(self.request, _('The item has been updated \o/'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('backoffice:wizard-items-list')

src/postix/backoffice/templates/backoffice/base.html
{% extends "core/base.html" %}

{% load staticfiles %}
{% load solo_tags %}
{% load i18n %}
{% load compress %}
{% get_solo 'core.EventSettings' as settings %}

{% block area_stylesheets %}
    {% compress css %}
        <link rel="stylesheet" type="text/x-scss" href="{% static "backoffice/scss/postix.scss" %}">
    {% endcompress %}
    {% block stylesheets %}
    {% endblock %}
{% endblock %}

{% block area_url %}{% url "backoffice:main" %}{% endblock %}
{% block area %}
    {% trans "Backoffice" %}
{% endblock %}

{% block area_content %}
        <div class="backoffice-main">
          {% if not settings.initialized and not user.is_anonymous %}
            <div class="alert alert-warning">
                {% if user.is_superuser %}
                    {% if request.path != '/backoffice/wizard/settings/' %}<a href="{% url "backoffice:wizard-settings" %}">{% endif %}
                    {% trans "Please initialize the event settings. postix will not be usable otherwise." %}
                    {% if request.path != '/backoffice/wizard/settings/' %}</a>{% endif %}
                {% else %}
                    {% trans "Please call a superuser to initialize this event's settings." %}
                {% endif %}
            </div>
          {% endif %}

          {% if settings.initialized or user.is_superuser or user.is_anonymous %}
            <h1>{% block headline %}{% endblock %}</h1>
            <div class="backoffice-content">
                {% if check_errors %}
                    <div class="alert alert-warning">
                        <strong>{% trans "We found some settings in your installation that are probably incorrect. We recommend that you check them again :)" %}</strong>
                        <ul>
                            {% for e in check_errors %}
                                <li>{{ e }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <p>
                {% block content %}
                {% endblock %}
                </p>
            </div>
          {% endif %}

        </div>
{% endblock %}
{% block area_scripts %}
    {% block scripts %}
    {% endblock %}
{% endblock %}

src/postix/backoffice/templates/backoffice/fail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>postix</title>
    <link rel="stylesheet" type="text/css" href="{% static "shared/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "shared/css/bootstrap-theme.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "shared/fonts/fonts.css" %}">
</head>
<body class="error">
<div class="error-page">
<span class="fa fa-eye-slash">
</span>

    <h2>{{ message }}</h2>
    {% if detail %}
        <p>{{ detail }}</p>
    {% endif %}
    {% if offer_logout %}
        <p><a href="{% url "backoffice:logout" %}" class="btn btn-default btn-lg">Log out</a></p>
    {% endif %}
</div>
<script type="text/javascript" src="{% static "shared/js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "backoffice/js/login.js" %}"></script>
</body>
</html>

src/postix/backoffice/templates/backoffice/login.html
{% extends "backoffice/base.html" %}
{% load staticfiles %}
{% load compress %}
{% block stylesheets %}
    {% compress css %}
        <link rel="stylesheet" type="text/x-scss" href="{% static "backoffice/scss/login.scss" %}">
    {% endcompress %}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <div class="logo">
                <img src="{% static "shared/img/logo.svg" %}">
            </div>

            <div class="account-wall">
                <form class="form-signin" action="" method="post" autocomplete="off">
                    {% csrf_token %}
                    <input type="text" class="form-control" placeholder="Username" required autofocus id="username"
                           autocomplete="off" name="username">
                    <input type="password" class="form-control" placeholder="Password" required id="password"
                           autocomplete="off" name="password">
                    <button class="btn btn-lg btn-primary btn-block" type="submit">
                        Sign in
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "backoffice/js/login.js" %}"></script>
{% endblock %}

src/postix/backoffice/templates/backoffice/main.html
{% extends 'backoffice/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block headline %} {% trans "Statistics" %}{% endblock %}

{% block content %}

{% if money %}
<div class="alert alert-info">
    {% blocktrans with money=money trimmed %}
    There is currently {{ money }} € in use as exchange money in cash desk sessions.
    {% endblocktrans %}
</div>
{% endif %}

<h3>{% trans "Products" %}</h3>

<ul>
    {% for product in products %}
    <li>
        {% blocktrans with redeemed=product.amount_redeemed sold=product.amount_sold name=product.name trimmed %}
        <strong>{{ name }}</strong> was sold {{ sold }} times and redeemed {{ redeemed }} times.
        {% endblocktrans %}

    </li>
    {% endfor %}
</ul>

    <h3>{% trans "Items" %}</h3>

    <ul>
        {% for item in items %}
            <li>
                {% blocktrans with redeemed=item.amount_redeemed sold=item.amount_sold name=item.name trimmed %}
                    <strong>{{ name }}</strong> was sold {{ sold }} times and redeemed {{ redeemed }} times.
                {% endblocktrans %}

            </li>
        {% endfor %}
    </ul>

    <h3>{% trans "Quotas" %}</h3>

    <ul>
        {% for quota in quotas %}
        <li>
            {% blocktrans with name=quota.name available=quota.amount_available size=quota.size trimmed %}
            <strong>{{ name }}</strong> is still available {{ available }} of {{ size }} times.
            {% endblocktrans %}

        </li>
        {% endfor %}
    </ul>

{% endblock %}

src/postix/backoffice/templates/backoffice/new_record_entity.html
{% extends 'backoffice/base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-md-2"></div>
<div class="col-md-8">
	<form method="post" action="">
	{% language "de" %}
	    {% csrf_token %}
        {% crispy form form.helper %}
        <input type="submit" name="submit" value="{% if form.instance.pk %}{% trans "Save entity" %}{% else %}{% trans "Create entity" %}{% endif %}" class="btn btn-primary btn-block" id="submit-save">
	{% endlanguage %}
	</form>
</div>
<div class="col-md-2"></div>
{% endblock %}

src/postix/backoffice/templates/backoffice/record_entity_list.html
{% extends 'backoffice/base.html' %}
{% load i18n %}

{% block content %}
<a href="{% url "backoffice:new-record-entity" %}" class="btn btn-primary pull-right">{% trans "New record entity" %}</a>
<table class="table" id="active-sessions-table">
    <thead>
        <th>{% trans "Name" %}</th>
        <th>{% trans "Detail" %}</th>
        <th></th>
    </thead>
    <tbody>
    {% language "de" %}
        {% for entity in entities %}
            <tr>
                <td>
                    {{ entity.name }}
                </td>
                <td>
                    {{ entity.detail }}
                </td>
                <td>
                    <a href="{% url "backoffice:record-entity-detail" pk=entity.pk %}" title="{% trans "Details" %}">
                        <span class="fa fa-2x fa-fw fa-pencil" aria-hidden="true"></span>
                    </a>
                    <a href="{% url "backoffice:record-entity-delete" pk=entity.pk %}" title="{% trans "Delete" %}">
                        <span class="fa fa-2x fa-fw fa-trash" aria-hidden="true"></span>
                    </a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <th colspan="42" class="empty-row active">
                    {% trans "No entities yet, get going!" %}
                </th>
            <tr>
        {% endfor %}
        {% endlanguage %}
    </tbody>
</table>

{% endblock %}

src/postix/backoffice/templates/backoffice/record_list.html
{% extends 'backoffice/base.html' %}
{% load i18n %}

{% block content %}
<a href="{% url "backoffice:new-record" %}" class="btn btn-primary pull-right">{% trans "New record" %}</a>
<table class="table" id="active-sessions-table">
    <thead>
        <th>{% trans "Date" %}</th>
        <th>{% trans "Entity" %}</th>
        <th>{% trans "User" %}</th>
        <th>{% trans "Carrier" %}</th>
        <th>{% trans "Inflow" %}</th>
        <th>{% trans "Outflow" %}</th>
        <th>{% trans "Saldo" %}</th>
        <th></th>
    </thead>
    <tbody>
    {% language "de" %}
        {% for record in records %}
            <tr>
                <td>
                    {% if record.datetime %}
                        {{ record.datetime|date:"Y-m-d H:i:s" }}
                    {% else %}
                        {{ record.end|date:"Y-m-d H:i:s" }}
                    {% endif %}
                </td>
                <td>
                    {% if record.entity %}
                        {{ record.entity }}
                    {% else %}
                        {% trans "Cashdesk session" %} #{{ record.pk}}
                    {% endif %}
                </td>
                <td>
                    {% if record.backoffice_user %}
                        {{ record.backoffice_user }}
                    {% else %}
                        {{ record.backoffice_user_after }}
                    {% endif %}
                </td>
                <td>
                    {% if record.carrier %}
                        {{ record.carrier }}
                    {% elif record.backoffice_user_after %}
                        {{ record.user.get_full_name }}
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>
                    {% if record.datetime and record.type == 'inflow' %}
                        {{ record.amount }}
                    {% elif record.end and record.amount >= 0 %}
                        {{ record.amount }}
                    {% endif %}
                </td>
                <td>
                    {% if record.type == 'outflow' or record.amount < 0 %}
                        {{ record.amount }}
                    {% endif %}
                </td>
                <td>
                    {{ record.running_total }}
                </td>
                <td>
                    {% if record.datetime %}
                        <a href="{% url "backoffice:record-detail" pk=record.pk %}" title="{% trans "Details" %}">
                            <span class="fa fa-2x fa-fw fa-pencil" aria-hidden="true"></span>
                        </a>
                        <a href="{% url "backoffice:record-print" pk=record.pk %}" title="{% trans "Print" %}">
                            <span class="fa fa-2x fa-fw fa-print" aria-hidden="true"></span>
                        </a>
                    {% else %}
                        <a href="{% url "backoffice:session-detail" pk=record.pk %}" title="{% trans "Details" %}">
                            <span class="fa fa-2x fa-fw fa-eye" aria-hidden="true"></span>
                        </a>
                        <a href="{% url "backoffice:end-session" pk=record.pk %}" title="{% trans "Edit" %}">
                            <span class="fa fa-2x fa-fw fa-pencil" aria-hidden="true"></span>
                        </a>
                        <a href="{% url "backoffice:session-report" pk=record.pk %}" title="{% trans "Report" %}">
                            <span class="fa fa-2x fa-fw fa-print" aria-hidden="true"></span>
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% empty %}
            <tr>
                <th colspan="42" class="empty-row active">
                    {% trans "No records yet, get going!" %}
                </th>
            <tr>
        {% endfor %}
        {% endlanguage %}
    </tbody>
</table>

{% endblock %}

src/postix/backoffice/templates/backoffice/wizard_cashdesks.html
{% extends 'backoffice/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block headline %} {% trans "Add a new cashdesk" %} {% endblock %}

{% block content %}{% crispy form %}{% endblock %}

src/postix/backoffice/templates/backoffice/wizard_item_list.html
{% extends 'backoffice/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headline %}{% trans "Item List" %}{% endblock %}

{% block content %}

<ul>
    {% for item in object_list %}
        <li>
            {{ item.name }}
            <a href="{% url "backoffice:wizard-items-edit" pk=item.pk %}" class="btn btn-default btn-xs">
                {% trans "Edit item" %}
            </a>
        </li>
    {% endfor %}

</ul>

{% endblock %}