src/postix/desk/urls.py
from django.conf.urls import url

from . import views

app_name = 'desk'
urlpatterns = [
    url('^login/', views.LoginView.as_view(), name='login'),
    url('^logout/', views.logout_view, name='logout'),
    url('^$', views.main_view, name='main'),
]

src/postix/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

admin.autodiscover()

js_info_dict = {
    'packages': (),
}

urlpatterns = [
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('postix.api.urls', namespace='api')),
    url(r'^backoffice/', include('postix.backoffice.urls', namespace='backoffice')),
    url(r'^troubleshooter/', include('postix.troubleshooter.urls', namespace='troubleshooter')),
    url(r'', include('postix.desk.urls', namespace='desk')),
]

src/postix/desk/views.py
from typing import Union

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.functional import cached_property
from django.utils.timezone import now
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView

from ..core.models import Cashdesk
from ..core.utils.iputils import detect_cashdesk, get_ip_address


class LoginView(TemplateView):
    template_name = 'desk/login.html'

    def dispatch(self, request: HttpRequest, *args, **kwargs) -> Union[HttpResponseRedirect, HttpResponse]:
        if not self.cashdesk:
            return render(request, 'desk/fail.html', {
                'message': _('This is not a registered cashdesk.'),
                'detail': _('Your IP address is {0}').format(get_ip_address(request))
            })
        if request.user.is_authenticated:
            return redirect('/')
        return super().dispatch(request, *args, **kwargs)

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponseRedirect:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if not user.is_active:
                messages.error(request, _('User account is deactivated.'))
                return redirect('desk:login')

            session = user.get_current_session()
            if session is None:
                messages.error(request, _('You do not have an active session.'))
                return redirect('desk:login')

            if session.cashdesk != self.cashdesk:
                messages.error(request, _('Your session is scheduled for a different cashdesk. Please go to '
                                          '{desk}').format(desk=str(session.cashdesk)))
                return redirect('desk:login')

            login(request, user)
            session.cashdesk.signal_next()
            return redirect('desk:main')
        else:
            messages.error(request, _('No user account matches the entered credentials.'))
        return redirect('desk:login')

    @cached_property
    def cashdesk(self) -> Cashdesk:
        return detect_cashdesk(self.request)


def logout_view(request: HttpRequest) -> HttpResponseRedirect:
    if request.user.is_authenticated:
        session = request.user.get_current_session()
    else:
        session = None
    logout(request)
    if session:
        session.cashdesk.signal_close()
    return redirect('desk:login')


@login_required(login_url='/login/')
def main_view(request: HttpRequest) -> HttpResponse:
    cashdesk = detect_cashdesk(request)
    session = request.user.get_current_session()
    if not cashdesk or session is None or session.cashdesk != cashdesk:
        return render(request, 'desk/fail.html', {
            'message': _('You do not have an active session at this cashdesk.'),
            'detail': _('You are logged in as {}.'.format(request.user)),
            'offer_logout': True
        })

    if not session.start:
        session.start = now()
        session.save(update_fields=['start'])

    return render(request, 'desk/main.html')

src/postix/troubleshooter/views/desk.py
from django.contrib import messages
from django.http import HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.utils.translation import ugettext as _

from ...core.models import CashdeskSession, TroubleshooterNotification
from .utils import troubleshooter_user_required


@troubleshooter_user_required
def check_requests(request: HttpRequest) -> JsonResponse:
    return JsonResponse({
        'has_requests': TroubleshooterNotification.objects.active().exists()
    })


@troubleshooter_user_required
def confirm_resupply(request: HttpRequest, pk: int) -> HttpResponseRedirect:
    if request.method == 'POST':
        try:
            session = CashdeskSession.objects.get(pk=pk)
        except CashdeskSession.DoesNotExist:
            messages.error(request, _('Unknown session.'))
        else:
            TroubleshooterNotification.objects.active(session=session).update(
                status=TroubleshooterNotification.STATUS_ACK,
                modified_by=request.user
            )
            messages.success(request, _('{} has been resupplied.').format(session.cashdesk))

    return redirect('troubleshooter:main')

src/postix/desk/templates/desk/fail.html
{% load staticfiles %}
{% load i18n %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>postix</title>
    {% compress css %}
        <link rel="stylesheet" type="text/css" href="{% static "shared/css/typeaheadjs.css" %}">
        <link rel="stylesheet" type="text/x-scss" href="{% static "shared/fontawesome/scss/font-awesome.scss" %}">
        <link rel="stylesheet" type="text/css" href="{% static "shared/fonts/fonts.css" %}">
        <link rel="stylesheet" type="text/x-scss" href="{% static "desk/scss/postix.scss" %}">
    {% endcompress %}
    <link rel="shortcut icon" href="{% static "shared/img/favicon.png" %}">
</head>
<body class="error">
<div class="error-page">
<span class="fa fa-power-off">
</span>

    <h2>{{ message }}</h2>
    {% if detail %}
        <p>{{ detail }}</p>
    {% endif %}
    {% if offer_logout %}
        <p><a href="{% url "desk:logout" %}" class="btn btn-default btn-lg">{% trans "Log out" %}</a></p>
    {% endif %}
</div>
<script type="text/javascript" src="{% static "shared/js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/login.js" %}"></script>
</body>
</html>

src/postix/desk/templates/desk/login.html
{% load staticfiles %}
{% load i18n %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>postix</title>
    {% compress css %}
        <link rel="stylesheet" type="text/css" href="{% static "shared/css/typeaheadjs.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "shared/fonts/fonts.css" %}">
        <link rel="stylesheet" type="text/x-scss" href="{% static "desk/scss/postix.scss" %}">
    {% endcompress %}
    <link rel="shortcut icon" href="{% static "shared/img/favicon.png" %}">
</head>
<body class="login">
<div class="logo">
    <img src="{% static "shared/img/logo.svg" %}">
</div>
<div class="panel panel-primary panel-login">
    <div class="panel-heading">
        <h3 class="panel-title">postix</h3>
    </div>
    <div class="panel-body">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <form action="" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="username" placeholder="{% trans "User name" %}" class="form-control"
                       id="username" autocomplete="off">
            </div>
            <div class="form-group">
                <input type="password" name="password" placeholder="{% trans "Password" %}" class="form-control"
                       id="password" autocomplete="off">
            </div>
            <button type="submit" class="btn btn-primary btn-lg btn-block">
                {% trans "Log In" %}
            </button>
        </form>
    </div>
</div>
<script type="text/javascript" src="{% static "shared/js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/login.js" %}"></script>
</body>
</html>

src/postix/desk/templates/desk/main.html
{% load staticfiles %}
{% load i18n %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>postix</title>
    {% compress css %}
        <link rel="stylesheet" type="text/css" href="{% static "shared/css/typeaheadjs.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "shared/fonts/fonts.css" %}">
        <link rel="stylesheet" type="text/x-scss" href="{% static "shared/fontawesome/scss/font-awesome.scss" %}">
        <link rel="stylesheet" type="text/x-scss" href="{% static "desk/scss/postix.scss" %}">
    {% endcompress %}
    <link rel="shortcut icon" href="{% static "shared/img/favicon.png" %}">
</head>
<body class="">

<div id="main-container">
    <div id="left-side">
        <div id="product-view">
            <div id="success-flash">
                <div>{% trans "Transaction complete" %}</div>
            </div>
            <div id="info-view">
                <div>
                    <div class="content"></div>
                    <button class="btn btn-default btn-lg btn-close">{% trans "Close" %}</button>
                </div>
            </div>
            <div id="product-view-inner"></div>
            <div class="upfade"></div>
            <div class="downfade"></div>
        </div>
        <div id="button-row">
            <a href="{% url "desk:logout" %}"><button class="btn btn-danger" id="btn-logout">
                <span class="fa fa-sign-out"></span>
                {% trans "Logout" %}
            </button></a>
            <button class="btn btn-default" id="btn-open-drawer">
                <span class="fa fa-inbox"></span>
                {% trans "Open drawer" %}
            </button>
            <button class="btn btn-info" id="btn-resupply">
                <span class="fa fa-bell"></span>
                {% trans "Request resupply" %}
            </button>
        </div>
    </div>
    <div id="right-side">
        <div id="redeem-presale">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    {% trans "Redeem preordered ticket" %}
                </div>
                <div class="panel-body">
                    <input type="text" id="preorder-input" class="typeahead form-control">
                </div>
            </div>
        </div>
        <div id="lower-right">
            <div class="panel panel-primary panel-sale">
                <div class="panel-heading">
                    <span>{% trans "Current transaction" %}</span>
                    <button class="btn btn-sm btn-default pull-right" id="btn-clear">
                        {% trans "clear" %}
                    </button>
                </div>
                <div class="panel-body">
                    <div id="cart">
                        <div id="cart-empty">
                            <p id="greeting">
                                {% blocktrans with name=request.user.username trimmed %}
                                    Welcome {{ name }}, have a nice day!
                                {% endblocktrans %}
                            </p>
                            <p id="clock"></p>
                        </div>
                        <div id="cart-inner"></div>
                        <div class="upfade"></div>
                         <div class="downfade"></div>
                    </div>
                    <div id="post-sale">
                        <div id="post-sale-total" class="total">
                            {% trans "Total:" %}
                            <span>267.40</span>
                        </div>
                        <div id="post-sale-given" class="total">
                            {% trans "Given:" %}
                            <input type="text" value="" class="form-control">
                        </div>
                        <div id="post-sale-change" class="total">
                            {% trans "Change:" %}
                            <span>0.00</span>
                        </div>
                        <div id="post-sale-reversed" class="total">
                            {% trans "REVERSED" %}
                        </div>
                        <div id="post-sale-buttons">
                            <button class="btn btn-block btn-default" id="btn-reverse">
                                <span class="fa fa-fast-backward"></span>
                                {% trans "Reverse" %}
                            </button>
                            <button class="btn btn-block btn-default" id="btn-reprint">
                                <span class="fa fa-files-o"></span>
                                {% trans "Reprint" %}
                            </button>
                        </div>
                    </div>
                    <div id="checkout">
                        <div id="checkout-total" class="total">
                            {% trans "Total:" %}
                            <span>267.40</span>
                        </div>
                        <button class="btn btn-block btn-success" id="btn-checkout">
                            <span class="fa fa-shopping-cart"></span>
                            {% trans "CHECKOUT" %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modal-container">
    <div id="modal">
        <div class="panel">
            <div class="panel-heading" id="modal-title">
                {% trans "Redeem preordered ticket" %}
            </div>
            <div class="panel-body">
                <p id="modal-text">
                </p>
                <p id="modal-input-wrapper">
                    <input type="text" id="modal-input" class="form-control"
                        autocomplete="dearchromeyoureallyshouldnotautocomplete">
                </p>

                <div id="modal-buttons">
                    <button class="btn btn-lg btn-primary" id="btn-dismiss">
                        {% trans "OK" %}
                    </button>
                    <button class="btn btn-lg btn-danger" id="btn-cancel">
                        {% trans "Cancel" %}
                    </button>
                    <button class="btn btn-lg btn-primary" id="btn-bypass">
                        {% trans "Upgrade" %}
                    </button>
                    <button class="btn btn-lg btn-success" id="btn-continue">
                        {% trans "Continue" %}
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="loading">
    <div>
        <span class="fa fa-spinner fa-spin"></span>
    </div>
</div>

<script type="text/javascript" src="{% static "shared/js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "shared/js/typeahead.bundle.min.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/loading.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/clock.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/productlist.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/preorder.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/transaction.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/dialog.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/actions.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/keyboard.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/commands.js" %}"></script>
<script type="text/javascript" src="{% static "desk/js/postix.js" %}"></script>
<script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
</body>
</html>