src/postix/backoffice/urls.py
from django.conf.urls import url

from . import views

app_name = 'backoffice'
urlpatterns = [
    url('^login/$', views.LoginView.as_view(), name='login'),
    url('^logout/$', views.logout_view, name='logout'),
    url('^switch-user/$', views.switch_user, name='switch-user'),

    url('^create_user/$', views.create_user_view, name='create-user'),
    url('^users/reset_password/(?P<pk>[0-9]+)/$', views.ResetPasswordView.as_view(), name='reset-password'),
    url('^users/$', views.UserListView.as_view(), name='user-list'),

    url('^session/new/$', views.new_session, name='new-session'),
    url('^session/(?P<pk>[0-9]+)/end/$', views.end_session, name='end-session'),
    url('^session/(?P<pk>[0-9]+)/report/$', views.session_report, name='session-report'),
    url('^session/(?P<pk>[0-9]+)/resupply/$', views.resupply_session, name='resupply-session'),
    url('^session/(?P<pk>[0-9]+)/move/$', views.move_session, name='move-session'),
    url('^session/(?P<pk>[0-9]+)/reverse/$', views.reverse_session_view, name='reverse-session'),
    url('^session/(?P<pk>[0-9]+)/$', views.SessionDetailView.as_view(), name='session-detail'),
    url('^session/$', views.SessionListView.as_view(), name='session-list'),
    url('^reports/$', views.ReportListView.as_view(), name='report-list'),

    url('^records/$', views.RecordListView.as_view(), name='record-list'),
    url('^records/new/$', views.RecordCreateView.as_view(), name='new-record'),
    url('^records/(?P<pk>[0-9]+)/$', views.RecordDetailView.as_view(), name='record-detail'),
    url('^records/(?P<pk>[0-9]+)/print/$', views.record_print, name='record-print'),
    url('^records/entity/$', views.RecordEntityListView.as_view(), name='record-entity-list'),
    url('^records/entity/new/$', views.RecordEntityCreateView.as_view(), name='new-record-entity'),
    url('^records/entity/(?P<pk>[0-9]+)/$', views.RecordEntityDetailView.as_view(), name='record-entity-detail'),
    url('^records/entity/(?P<pk>[0-9]+)/delete/$', views.RecordEntityDeleteView.as_view(), name='record-entity-delete'),

    # These are called 'wizard' cause they're only for wizards (erm, superusers)
    url('^wizard/users/$', views.WizardUsersView.as_view(), name='wizard-users'),
    url('^wizard/settings/$', views.WizardSettingsView.as_view(), name='wizard-settings'),
    url('^wizard/cashdesks/$', views.WizardCashdesksView.as_view(), name='wizard-cashdesks'),
    url('^wizard/import/$', views.WizardPretixImportView.as_view(), name='wizard-import'),
    url('^wizard/items/$', views.WizardItemListView.as_view(), name='wizard-items-list'),
    url('^wizard/items/new$', views.WizardItemCreateView.as_view(), name='wizard-items-create'),
    url('^wizard/items/(?P<pk>[0-9]+)/$', views.WizardItemEditView.as_view(), name='wizard-items-edit'),

    url('^$', views.MainView.as_view(), name='main'),
]

src/postix/desk/urls.py
from django.conf.urls import url

from . import views

app_name = 'desk'
urlpatterns = [
    url('^login/', views.LoginView.as_view(), name='login'),
    url('^logout/', views.logout_view, name='logout'),
    url('^$', views.main_view, name='main'),
]

src/postix/troubleshooter/urls.py
from django.conf.urls import url

from . import views

app_name = 'troubleshooter'
urlpatterns = [
    url('^login/$', views.LoginView.as_view(), name='login'),
    url('^logout/$', views.logout_view, name='logout'),

    url('^ping/$', views.PingView.as_view(), name='ping'),

    url('^preorders/$', views.PreorderListView.as_view(), name='preorder-list'),
    url('^preorders/information/$', views.PreorderInformationListView.as_view(), name='preorder-information-list'),
    url('^preorders/(?P<pk>[0-9]+)/$', views.PreorderDetailView.as_view(), name='preorder-detail'),

    url('^constraints/(?P<pk>[0-9]+)/$', views.ListConstraintDetailView.as_view(), name='constraint-detail'),
    url('^constraints/$', views.ListConstraintListView.as_view(), name='constraint-list'),

    url('^information/(?P<pk>[0-9]+)/$', views.InformationDetailView.as_view(), name='information-detail'),
    url('^information/$', views.InformationListView.as_view(), name='information-list'),

    url('^transactions/(?P<pk>[0-9]+)/reprint/$', views.transaction_reprint, name='transaction-reprint'),
    url('^transactions/(?P<pk>[0-9]+)/invoice/$', views.transaction_invoice, name='transaction-invoice'),
    url('^transactions/(?P<pk>[0-9]+)/$', views.TransactionDetailView.as_view(), name='transaction-detail'),
    url('^transactions/$', views.TransactionListView.as_view(), name='transaction-list'),

    url('^session/(?P<pk>[0-9]+)/resupply/$', views.confirm_resupply, name='confirm-resupply'),
    url('^session/check_requests$', views.check_requests, name='check-requests'),

    url('^$', views.main_view, name='main'),
]

src/postix/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

admin.autodiscover()

js_info_dict = {
    'packages': (),
}

urlpatterns = [
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('postix.api.urls', namespace='api')),
    url(r'^backoffice/', include('postix.backoffice.urls', namespace='backoffice')),
    url(r'^troubleshooter/', include('postix.troubleshooter.urls', namespace='troubleshooter')),
    url(r'', include('postix.desk.urls', namespace='desk')),
]

src/postix/core/models/base.py
import os
from decimal import Decimal
from typing import Union

from django.core.files.storage import default_storage
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Max, Sum
from django.utils import timezone
from django.utils.functional import cached_property

from ..utils import round_decimal


class Transaction(models.Model):
    datetime = models.DateTimeField(auto_now_add=True)
    cash_given = models.DecimalField(null=True, max_digits=10, decimal_places=2)
    session = models.ForeignKey('CashdeskSession', related_name='transactions',
                                on_delete=models.PROTECT)
    receipt_id = models.PositiveIntegerField(null=True, blank=True, unique=True)

    def print_receipt(self, do_open_drawer: bool=True) -> None:
        self.session.cashdesk.printer.print_receipt(self, do_open_drawer)

    @property
    def value(self) -> Decimal:
        return self.positions.aggregate(result=Sum('value'))['result']

    @property
    def has_reversed_positions(self) -> bool:
        return any(tp.was_reversed() for tp in self.positions.all())

    @property
    def has_reversals(self) -> bool:
        return self.positions.filter(type='reverse').exists()

    @property
    def can_be_reversed(self) -> bool:
        return (not self.has_reversals) and (not self.has_reversed_positions)

    @property
    def has_invoice(self) -> bool:
        return bool(self.get_invoice_path())

    def get_invoice_path(self, allow_nonexistent: bool=False) -> Union[str, None]:
        if self.receipt_id:
            base = default_storage.path('invoices')
            path = os.path.join(base, 'invoice_{:04d}.pdf'.format(self.receipt_id))
            if allow_nonexistent or os.path.exists(path):
                return path
        return ''

    def set_receipt_id(self, retry: int=0) -> None:
        try:
            self.receipt_id = 1 + (Transaction.objects.aggregate(m=Max('receipt_id'))['m'] or 0)
            self.save(update_fields=['receipt_id'])
        except Exception as e:
            if retry > 0:
                self.set_receipt_id(retry=retry - 1)
            else:
                raise e


class TransactionPosition(models.Model):
    TYPES = (
        ('redeem', 'Presale redemption'),
        ('reverse', 'Reversal'),
        ('sell', 'Sale')
    )

    transaction = models.ForeignKey('Transaction', related_name='positions',
                                    on_delete=models.PROTECT)
    type = models.CharField(choices=TYPES, max_length=100)
    value = models.DecimalField(max_digits=10, decimal_places=2)
    tax_rate = models.DecimalField(max_digits=4, decimal_places=2,
                                   validators=[MinValueValidator(Decimal('0.00'))])
    tax_value = models.DecimalField(max_digits=10, decimal_places=2)
    product = models.ForeignKey('Product', related_name='positions',
                                on_delete=models.PROTECT)
    reverses = models.ForeignKey('TransactionPosition', related_name='reversed_by',
                                 on_delete=models.PROTECT, null=True, blank=True)
    listentry = models.ForeignKey('ListConstraintEntry', related_name='positions',
                                  on_delete=models.PROTECT, null=True, blank=True)
    preorder_position = models.ForeignKey('PreorderPosition', related_name='transaction_positions',
                                          on_delete=models.PROTECT, null=True, blank=True)
    items = models.ManyToManyField('Item', through='TransactionPositionItem',
                                   blank=True)
    authorized_by = models.ForeignKey('User', null=True, blank=True, on_delete=models.PROTECT,
                                      related_name='authorized')
    has_constraint_bypass = models.BooleanField(default=False)

    def calculate_tax(self) -> None:
        net_value = self.value * 100 / (100 + self.tax_rate)
        self.tax_value = round_decimal(self.value - net_value)

    def save(self, *args, **kwargs) -> None:
        if self.type == 'reverse':
            self.product = self.reverses.product
            if self.value is None:
                self.value = -self.reverses.value
        if self.value is None:
            self.value = self.product.price
        if self.tax_rate is None:
            self.tax_rate = self.product.tax_rate

        self.calculate_tax()

        super(TransactionPosition, self).save(*args, **kwargs)

        if not self.items.exists():
            for pi in self.product.product_items.all().select_related('item'):
                TransactionPositionItem.objects.create(
                    position=self, item=pi.item, amount=pi.amount
                )

    def was_reversed(self) -> bool:
        if self.type == 'reverse':
            return False

        return TransactionPosition.objects.filter(reverses=self, type='reverse').exists()


class Product(models.Model):
    name = models.CharField(max_length=254)
    receipt_name = models.CharField(max_length=28)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    tax_rate = models.DecimalField(max_digits=4, decimal_places=2,
                                   verbose_name='Tax rate',
                                   help_text='in percent',
                                   validators=[MinValueValidator(Decimal('0.00'))])
    is_visible = models.BooleanField(default=True)
    requires_authorization = models.BooleanField(default=False)
    items = models.ManyToManyField('Item', through='ProductItem', blank=True)
    priority = models.IntegerField(default=0, verbose_name='Priority',
                                   help_text='Will be used for sorting, high priorities come first.')
    import_source_id = models.CharField(max_length=180, db_index=True, null=True, blank=True)

    def save(self, *args, **kwargs) -> None:
        if not self.receipt_name:
            self.receipt_name = self.name[:28]
        super().save(*args, **kwargs)

    @property
    def is_availably_by_time(self) -> bool:
        from . import TimeConstraint
        timeframes = TimeConstraint.objects.filter(products=self)
        if timeframes.exists():
            now = timezone.now()
            current_timeframes = timeframes.filter(start__lte=now, end__gte=now)
            if not current_timeframes.exists():
                return False

        return True

    @property
    def is_available(self) -> bool:
        from . import Quota
        quotas = Quota.objects.filter(products=self)
        if quotas.exists():
            all_quotas_available = all([quota.is_available() for quota in quotas])
            if not all_quotas_available:
                return False

        return self.is_visible and self.is_availably_by_time

    @cached_property
    def amount_sold(self) -> int:
        positive = self.positions.filter(type='sell').count()
        negative = self.positions.filter(type='reverse').exclude(preorder_position__isnull=False).count()
        return positive - negative

    @cached_property
    def amount_redeemed(self) -> int:
        positive = self.positions.filter(type='redeem').count()
        negative = self.positions.filter(type='reverse').exclude(preorder_position__isnull=True).count()
        return positive - negative

    @property
    def pack_list(self) -> str:
        result = []
        for item in self.product_items.all():
            if item.is_visible:
                if item.amount != 1:
                    result.append("{}x {}".format(item.amount, item.item.name))
                else:
                    result.append(item.item.name)
        return ", ".join(result)

    @property
    def needs_receipt(self) -> bool:
        return not self.product_items.filter(item__is_receipt=True).exists()

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ('-priority', 'pk')


class Item(models.Model):
    name = models.CharField(max_length=254)
    description = models.TextField(blank=True)
    initial_stock = models.PositiveIntegerField()
    is_receipt = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name

    @cached_property
    def amount_sold(self) -> int:
        positive = self.transaction_position_items.filter(position__type='sell').count()
        negative = self.transaction_position_items.filter(position__type='reverse').exclude(position__preorder_position__isnull=False).count()
        return positive - negative

    @cached_property
    def amount_redeemed(self) -> int:
        positive = self.transaction_position_items.filter(position__type='redeem').count()
        negative = self.transaction_position_items.filter(position__type='reverse').exclude(position__preorder_position__isnull=True).count()
        return positive - negative


class ProductItem(models.Model):
    product = models.ForeignKey('Product', on_delete=models.PROTECT,
                                related_name='product_items')
    item = models.ForeignKey('Item', on_delete=models.PROTECT,
                             related_name='product_items')
    is_visible = models.BooleanField(default=True,
                                     help_text='If activated, this item will be shown in the frontend')
    amount = models.PositiveIntegerField()


class TransactionPositionItem(models.Model):
    position = models.ForeignKey('TransactionPosition', on_delete=models.PROTECT,
                                 related_name='transaction_position_items')
    item = models.ForeignKey('Item', on_delete=models.PROTECT,
                             related_name='transaction_position_items')
    amount = models.IntegerField()

src/postix/core/models/info.py
from django.db import models


class Info(models.Model):
    content = models.CharField(max_length=2500)
    name = models.CharField(max_length=40, null=True, blank=True)
    is_printable = models.BooleanField(default=True)

src/postix/core/models/ping.py
from tempfile import TemporaryFile

import qrcode
from django.db import models
from django.utils.crypto import get_random_string
from django.utils.timezone import now

from .cashdesk import Cashdesk

MAX_LENGTH = 20


def generate_ping(cashdesk: Cashdesk) -> None:
    ping = Ping.objects.create()
    cashdesk.printer.print_image(ping.get_qr_code())


def generate_ping_secret():
    prefix = '/ping '
    return prefix + get_random_string(length=MAX_LENGTH - len(prefix))


class Ping(models.Model):
    pinged = models.DateTimeField(auto_now_add=True)
    ponged = models.DateTimeField(null=True, blank=True)
    secret = models.CharField(max_length=MAX_LENGTH, default=generate_ping_secret)

    def get_qr_code(self):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=5,
            border=4,
        )
        qr.add_data(self.secret)
        qr.make()
        f = TemporaryFile()
        img = qr.make_image()
        img.save(f)
        return f

    def pong(self):
        if not self.ponged:
            self.ponged = now()
            self.save()

src/postix/core/models/settings.py
from django.db import models
from solo.models import SingletonModel


class EventSettings(SingletonModel):
    name = models.CharField(max_length=100, default='Generic Event')
    short_name = models.CharField(
        max_length=50,
        default='GE',
        help_text='A short name for your event.',
    )
    support_contact = models.CharField(
        max_length=200,
        default='Who is flying this thing? Enter your contact information as support contact info, please.',
        help_text='Your - yes YOUR - real-time contact info, e.g. phone number.',
    )
    invoice_address = models.CharField(max_length=200, blank=True, null=True)
    invoice_footer = models.CharField(max_length=200, blank=True, null=True)
    receipt_address = models.CharField(max_length=200, blank=True, null=True)
    receipt_footer = models.CharField(
        max_length=200,
        default='Thank you!',
        help_text='Use this to display additional disclaimers/data not in your address, such as VAT IDs.',
    )
    report_footer = models.CharField(
        max_length=500,
        default='CCC Veranstaltungsgesellschaft mbH',
        help_text='This will show up on backoffice session reports.'
    )
    initialized = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Event Settings'

src/postix/core/templates/core/base.html
{% load staticfiles %}
{% load solo_tags %}
{% load i18n %}
{% load compress %}
{% get_solo 'core.EventSettings' as settings %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>postix {% block title %}{% endblock %}</title>

    {% compress css %}
        <link rel="stylesheet" type="text/css" href="{% static "shared/fonts/fonts.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "shared/css/core.css" %}">
    {% endcompress %}
    {% block area_stylesheets %}
    {% endblock %}
    <link rel="shortcut icon" href="{% static "shared/img/favicon.png" %}">

</head>
<body><div id="wrapper">
    <nav class="navbar navbar-inverse navbar-static-top">
        <a class="navbar-brand" href="{% block area_url %}{% endblock %}">
            <img src="{% static "shared/img/icon_white.svg" %}">
            {% block area %}{% endblock %}
        </a>
        <div id="navbar" class="">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_superuser %}
                    {% if not settings.initialized %}
                        <li><a href="{% url "backoffice:wizard-settings" %}"><span class="text-danger fa fa-bell"></span></a></li>
                    {% endif %}
                {% endif %}
                {% if not request.user.is_anonymous %}
                    <li>
                        <a href="{% if request.user.is_backoffice_user or request.user.is_superuser %}{% url "backoffice:logout" %}{% else %}{% url "troubleshooter:logout" %}{% endif %}">
                            <span class="fa fa-sign-out"></span> {{ user }}
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div id="page-wrapper">
        {% if not user.is_anonymous %}
        <nav class="nav flex-column sidebar">
            {% if user.is_backoffice_user or user.is_superuser %}
                <span class="nav-link">
                    <span class="fa fa-fw fa-handshake-o"></span>
                    {% trans "Sessions" %}
                </span>
                    <a class="nav-link subnav" href="{% url "backoffice:new-session" %}">
                        <span class="fa fa-fw fa-plus-circle"></span>
                        {% trans "New session" %}
                    </a>
                    <a class="nav-link subnav" href="{% url "backoffice:session-list" %}">
                        <span class="fa fa-fw fa-list"></span>
                        {% trans "List of sessions" %}
                    </a>
                    <a class="nav-link subnav" href="{% url "backoffice:report-list" %}">
                        <span class="fa fa-fw fa-book"></span>
                        {% trans "Reports" %}
                    </a>
                <span class="nav-link">
                    <span class="fa fa-fw fa-handshake-o"></span>
                    {% trans "Records" %}
                </span>
                    <a class="nav-link subnav" href="{% url "backoffice:new-record" %}">
                        <span class="fa fa-fw fa-plus-circle"></span>
                        {% trans "New record" %}
                    </a>
                    <a class="nav-link subnav" href="{% url "backoffice:record-list" %}">
                        <span class="fa fa-fw fa-list"></span>
                        {% trans "List of records" %}
                    </a>
                <span class="nav-link">
                    <span class="fa fa-fw fa-users"></span>
                    {% trans "Users" %}
                </span>
                    <a class="nav-link subnav" href="{% url "backoffice:create-user" %}">
                        <span class="fa fa-fw fa-plus-circle"></span>
                        {% trans "New user" %}
                    </a>
                    <a class="nav-link subnav" href="{% url "backoffice:user-list" %}">
                        <span class="fa fa-fw fa-list"></span>
                        {% trans "User list" %}
                    </a>
            {% endif %}
            {% if user.is_troubleshooter or user.is_superuser %}
                {% if user.is_superuser or user.is_backoffice_user %}
                    <span class="nav-link">
                        <span class="fa fa-fw fa-user-secret"></span>
                        {% trans "Troubleshooting" %}
                    </span>
                {% endif %}
                <a href="{% url "troubleshooter:main" %} "id="nav-sessions" class="nav-link subnav{% if has_request %} has-request{% endif %}">
                    <span class="fa fa-fw fa-user"></span>
                    {% trans "Current sessions" %}
                </a>
                <a class="nav-link subnav" href="{% url "troubleshooter:transaction-list" %}">
                    <span class="fa fa-fw fa-book"></span>
                    {% trans "Transactions" %}
                </a>
                <a class="nav-link subnav" href="{% url "troubleshooter:constraint-list" %}">
                    <span class="fa fa-fw fa-list"></span>
                    {% trans "Lists" %}
                </a>
                <a class="nav-link subnav" href="{% url "troubleshooter:preorder-list" %}">
                    <span class="fa fa-fw fa-shopping-cart"></span>
                    {% trans "Preorder" %}
                </a>
                <a class="nav-link subnav" href="{% url "troubleshooter:preorder-information-list" %}">
                    <span class="fa fa-fw fa-shopping-cart"></span>
                    {% trans "Preorder Specials" %}
                </a>
                <a class="nav-link subnav" href="{% url "troubleshooter:ping" %}">
                    <span class="fa fa-fw fa-terminal"></span>
                    {% trans "Ping" %}
                </a>
                <a class="nav-link subnav" href="{% url "troubleshooter:information-list" %}">
                    <span class="fa fa-fw fa-print"></span>
                    {% trans "Print" %}
                </a>
            {% endif %}
            {% if user.is_superuser %}
                <span class="nav-link" href="{% url "backoffice:wizard-settings" %}">
                    <span class="fa fa-fw fa-cog"></span>
                    {% trans "Settings" %}
                </span>
                <a class="nav-link subnav" href="{% url "backoffice:wizard-settings" %}">
                    <span class="fa fa-fw fa-cogs"></span>
                    {% trans "General Settings" %}
                </a>
                <a class="nav-link subnav" href="{% url "backoffice:wizard-users" %}">
                    <span class="fa fa-fw fa-users"></span>
                    {% trans "User Permissions" %}
                </a>
                <a class="nav-link subnav" href="{% url "backoffice:wizard-cashdesks" %}">
                    <span class="fa fa-fw fa-plus-circle"></span>
                    {% trans "New Cashdesks" %}
                </a>
                <a class="nav-link subnav" href="{% url "backoffice:wizard-import" %}">
                    <span class="fa fa-fw fa-download"></span>
                    {% trans "Import Presale Data" %}
                </a>
                <a class="nav-link subnav" href="{% url "backoffice:wizard-items-list" %}">
                    <span class="fa fa-fw fa-list"></span>
                    {% trans "Item List" %}
                </a>
                <a class="nav-link subnav" href="{% url "backoffice:wizard-items-create" %}">
                    <span class="fa fa-fw fa-plus-circle"></span>
                    {% trans "Add an Item" %}
                </a>
                <a class="nav-link subnav" href="{% url "backoffice:record-entity-list" %}">
                    <span class="fa fa-fw fa-list"></span>
                    {% trans "Record Entities" %}
                </a>
            {% endif %}
        </nav>
        {% endif %}

    <div class="container" id="page-content">

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        {% block area_content %}
        {% endblock %}

    <script type="text/javascript" src="{% static "shared/js/jquery.min.js" %}"></script>
    {% block area_scripts %}
    {% endblock %}

</div></body>
</html>

src/postix/core/templates/core/pagination.html
{% load urlreplace %}
{% load i18n %}
{% if is_paginated %}
    <div class="pagination">
        {% if page_obj.has_previous %}
            <a href="?{% urlreplace request "page" page_obj.previous_page_number %}">
                <span class="fa fa-arrow-left" aria-hidden="true"></span>
            </a>
        {% endif %}
        <span class="page-current">
            {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ page_obj.paginator.num_pages }}.
		</span>
        {% if page_obj.has_next %}
            <a href="?{% urlreplace request "page" page_obj.next_page_number %}">
                <span class="fa fa-arrow-right" aria-hidden="true"></span>
            </a>
        {% endif %}
    </div>
{% endif %}