src/postix/troubleshooter/urls.py
from django.conf.urls import url

from . import views

app_name = 'troubleshooter'
urlpatterns = [
    url('^login/$', views.LoginView.as_view(), name='login'),
    url('^logout/$', views.logout_view, name='logout'),

    url('^ping/$', views.PingView.as_view(), name='ping'),

    url('^preorders/$', views.PreorderListView.as_view(), name='preorder-list'),
    url('^preorders/information/$', views.PreorderInformationListView.as_view(), name='preorder-information-list'),
    url('^preorders/(?P<pk>[0-9]+)/$', views.PreorderDetailView.as_view(), name='preorder-detail'),

    url('^constraints/(?P<pk>[0-9]+)/$', views.ListConstraintDetailView.as_view(), name='constraint-detail'),
    url('^constraints/$', views.ListConstraintListView.as_view(), name='constraint-list'),

    url('^information/(?P<pk>[0-9]+)/$', views.InformationDetailView.as_view(), name='information-detail'),
    url('^information/$', views.InformationListView.as_view(), name='information-list'),

    url('^transactions/(?P<pk>[0-9]+)/reprint/$', views.transaction_reprint, name='transaction-reprint'),
    url('^transactions/(?P<pk>[0-9]+)/invoice/$', views.transaction_invoice, name='transaction-invoice'),
    url('^transactions/(?P<pk>[0-9]+)/$', views.TransactionDetailView.as_view(), name='transaction-detail'),
    url('^transactions/$', views.TransactionListView.as_view(), name='transaction-list'),

    url('^session/(?P<pk>[0-9]+)/resupply/$', views.confirm_resupply, name='confirm-resupply'),
    url('^session/check_requests$', views.check_requests, name='check-requests'),

    url('^$', views.main_view, name='main'),
]

src/postix/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

admin.autodiscover()

js_info_dict = {
    'packages': (),
}

urlpatterns = [
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('postix.api.urls', namespace='api')),
    url(r'^backoffice/', include('postix.backoffice.urls', namespace='backoffice')),
    url(r'^troubleshooter/', include('postix.troubleshooter.urls', namespace='troubleshooter')),
    url(r'', include('postix.desk.urls', namespace='desk')),
]

src/postix/troubleshooter/forms.py
from django import forms

from postix.core.models import Cashdesk


class InvoiceAddressForm(forms.Form):
    address = forms.CharField(widget=forms.Textarea)


class CashdeskForm(forms.Form):
    cashdesk = forms.ModelChoiceField(queryset=Cashdesk.objects.all())


class PrintForm(forms.Form):
    cashdesk = forms.ModelChoiceField(queryset=Cashdesk.objects.all())
    amount = forms.IntegerField(min_value=1, max_value=50)

src/postix/troubleshooter/views/constraints.py
from typing import Any, Dict

from django.contrib import messages
from django.db.models import Q
from django.utils.translation import ugettext as _
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from ...core.models import ListConstraint
from .utils import TroubleshooterUserRequiredMixin


class ListConstraintListView(TroubleshooterUserRequiredMixin, ListView):
    template_name = 'troubleshooter/constraints_list.html'
    context_object_name = 'constraints'
    model = ListConstraint


class ListConstraintDetailView(TroubleshooterUserRequiredMixin, DetailView):
    template_name = 'troubleshooter/constraint_detail.html'
    context_object_name = 'constraint'
    model = ListConstraint

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['restricted'] = False
        obj = kwargs['object']

        if self.request.GET and self.request.GET['filter']:
            query = self.request.GET['filter']

            if obj.confidential and len(query) < 3:
                ctx['entries'] = []
                ctx['restricted'] = True
                messages.error(self.request, _('Search strings must be 3 characters or longer for confidential lists.'))
            else:
                ctx['entries'] = obj.entries.filter(
                    Q(name__icontains=query) | Q(identifier__icontains=query)
                )
                if obj.confidential:
                    ctx['entries'] = ctx['entries'][:10]
                    ctx['restricted'] = ctx['entries'].count() > 10
        else:
            if obj.confidential:
                ctx['entries'] = []
                ctx['restricted'] = True
            else:
                ctx['entries'] = obj.entries.all()
        return ctx

src/postix/troubleshooter/views/desk.py
from django.contrib import messages
from django.http import HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.utils.translation import ugettext as _

from ...core.models import CashdeskSession, TroubleshooterNotification
from .utils import troubleshooter_user_required


@troubleshooter_user_required
def check_requests(request: HttpRequest) -> JsonResponse:
    return JsonResponse({
        'has_requests': TroubleshooterNotification.objects.active().exists()
    })


@troubleshooter_user_required
def confirm_resupply(request: HttpRequest, pk: int) -> HttpResponseRedirect:
    if request.method == 'POST':
        try:
            session = CashdeskSession.objects.get(pk=pk)
        except CashdeskSession.DoesNotExist:
            messages.error(request, _('Unknown session.'))
        else:
            TroubleshooterNotification.objects.active(session=session).update(
                status=TroubleshooterNotification.STATUS_ACK,
                modified_by=request.user
            )
            messages.success(request, _('{} has been resupplied.').format(session.cashdesk))

    return redirect('troubleshooter:main')

src/postix/troubleshooter/views/information.py
from django.contrib import messages
from django.urls import reverse
from django.views.generic import FormView
from django.views.generic.list import ListView

from postix.core.models import Info
from postix.troubleshooter.forms import PrintForm
from postix.troubleshooter.views.utils import TroubleshooterUserRequiredMixin


class InformationListView(TroubleshooterUserRequiredMixin, ListView):
    template_name = 'troubleshooter/information_list.html'
    context_object_name = 'information'
    paginate_by = 50
    model = Info
    queryset = Info.objects.all().order_by('id')


class InformationDetailView(TroubleshooterUserRequiredMixin, FormView):
    template_name = 'troubleshooter/information_detail.html'
    form_class = PrintForm

    def get_context_data(self):
        ctx = super().get_context_data()
        ctx['information'] = Info.objects.get(pk=self.kwargs['pk'])
        return ctx

    def post(self, request, pk):
        form = self.get_form()
        if form.is_valid():
            info = Info.objects.get(pk=self.kwargs['pk'])
            cashdesk = form.cleaned_data.get('cashdesk')
            amount = form.cleaned_data.get('amount')
            for _ in range(amount):
                cashdesk.printer.print_text(info.content)
            messages.success(request, 'Done.')
            return self.form_valid(form)

        else:
            messages.error(request, form.errors)
            return self.form_valid(form)

    def get_success_url(self):
        return reverse('troubleshooter:information-detail', kwargs=self.kwargs)

src/postix/troubleshooter/views/ping.py
from django.urls import reverse
from django.views.generic import FormView

from postix.core.models.ping import Ping, generate_ping
from postix.troubleshooter.forms import CashdeskForm
from postix.troubleshooter.views.utils import TroubleshooterUserRequiredMixin


def get_minutes(timedelta):
    return timedelta.total_seconds() // 60


class PingView(TroubleshooterUserRequiredMixin, FormView):
    template_name = 'troubleshooter/ping.html'
    form_class = CashdeskForm

    def get_context_data(self):
        ctx = super().get_context_data()
        if Ping.objects.exists():
            pings = Ping.objects.order_by('pinged')
            ping_count = pings.count()
            ping_success = pings.filter(ponged__isnull=False)
            ping_success_count = ping_success.count()

            durations = [get_minutes(p.ponged - p.pinged) for p in ping_success]

            ctx['pings'] = pings
            ctx['ping_success'] = ping_success_count
            ctx['loss_percent'] = '{:.2f}'.format((ping_count - ping_success_count) * 100 / ping_count)

            if durations:
                ctx['total_min'] = min(durations)
                ctx['total_max'] = max(durations)
                ctx['total_avg'] = sum(durations) / len(durations)
                ctx['total_mdev'] = sum(((duration - ctx['total_avg']) ** 2) for duration in durations) / len(durations)
        else:
            ctx['pings'] = []
            ctx['ping_success'] = 0

        return ctx

    def post(self, request):
        form = self.get_form()
        if form.is_valid():
            cashdesk = form.cleaned_data.get('cashdesk')
            generate_ping(cashdesk)
            return self.form_valid(form)

    def get_success_url(self):
        return reverse('troubleshooter:ping')

src/postix/troubleshooter/views/preorders.py
from django.contrib import messages
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.utils.translation import ugettext as _
from django.views.generic import DetailView, ListView

from ...core.models import Preorder, PreorderPosition
from ..forms import CashdeskForm
from .utils import TroubleshooterUserRequiredMixin


class PreorderListView(TroubleshooterUserRequiredMixin, ListView):
    template_name = 'troubleshooter/preorders.html'
    context_object_name = 'preorders'
    model = Preorder

    def dispatch(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        self.filter = dict()
        _filter = self.request.GET
        if 'code' in _filter and _filter['code']:
            if len(_filter['code']) < 4:
                messages.error(request, _('You need to enter at least four characters of the order code.'))
            else:
                self.filter['code'] = _filter['code']
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet:
        qs = Preorder.objects.all().order_by('order_code')
        if 'code' in self.filter:
            qs = qs.filter(order_code__icontains=self.filter['code'])
        else:
            qs = qs.none()
        return qs


class PreorderInformationListView(TroubleshooterUserRequiredMixin, ListView):
    template_name = 'troubleshooter/preorder_information.html'
    context_object_name = 'positions'
    model = PreorderPosition
    queryset = PreorderPosition.objects.all().exclude(information__isnull=True).exclude(information='')

    def get_context_data(self):
        ctx = super().get_context_data()
        ctx['form'] = CashdeskForm()
        return ctx

    def post(self, request, *args, **kwargs):
        form = CashdeskForm(request.POST)
        if form.is_valid():
            form.cleaned_data['cashdesk'].printer.print_attendance(
                arrived=[position for position in self.queryset if position.is_redeemed],
                not_arrived=[position for position in self.queryset if not position.is_redeemed],
            )
            messages.success(request, _('Attendance print in progress.'))
        else:
            messages.error(request, _('Please specify a cashdesk.'))
        return redirect(request.path)


class PreorderDetailView(TroubleshooterUserRequiredMixin, DetailView):
    template_name = 'troubleshooter/preorder_detail.html'
    context_object_name = 'preorder'
    model = Preorder

src/postix/troubleshooter/views/transactions.py
from typing import Any, Dict, Union

from django.contrib import messages
from django.core.files.storage import default_storage
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.translation import ugettext as _
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from ...core.models import (
    Cashdesk, CashdeskSession, Transaction, TransactionPosition,
)
from ..forms import InvoiceAddressForm
from ..invoicing import generate_invoice
from .utils import (
    TroubleshooterUserRequiredMixin, troubleshooter_user_required,
)


class TransactionListView(TroubleshooterUserRequiredMixin, ListView):
    template_name = 'troubleshooter/transaction_list.html'
    context_object_name = 'transactions'
    paginate_by = 50

    def dispatch(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        self.filter = dict()
        _filter = self.request.GET
        types = [t[0] for t in TransactionPosition.TYPES]

        if 'type' in _filter and _filter['type'] in types:
            self.filter['type'] = _filter['type']

        if 'desk' in _filter and _filter['desk']:
            try:
                desk = Cashdesk.objects.get(pk=_filter['desk'])
                self.filter['cashdesk'] = desk
            except Cashdesk.DoesNotExist:
                pass
        if 'receipt' in _filter and _filter['receipt']:
            try:
                self.filter['receipt'] = int(_filter['receipt'])
            except (TypeError, ValueError):
                messages.error(request, _('Receipt ID has to be an integer.'))
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet:
        qs = TransactionPosition.objects.all()\
            .order_by('-transaction__datetime')\
            .select_related('transaction')
        if 'cashdesk' in self.filter:
            qs = qs.filter(transaction__session__cashdesk=self.filter['cashdesk'])
        if 'type' in self.filter and self.filter['type']:
            qs = qs.filter(type=self.filter['type'])
        if 'receipt' in self.filter and self.filter['receipt']:
            qs = qs.filter(transaction__receipt_id=self.filter['receipt'])
        return qs

    def get_context_data(self) -> Dict[str, Any]:
        ctx = super().get_context_data()
        ctx['cashdesks'] = Cashdesk.objects.all()
        ctx['types'] = [t[0] for t in TransactionPosition.TYPES]
        return ctx


class TransactionDetailView(TroubleshooterUserRequiredMixin, DetailView):
    template_name = 'troubleshooter/transaction_detail.html'
    context_object_name = 'transaction'
    model = Transaction

    def get_context_data(self, object):
        ctx = super().get_context_data()
        ctx['sessions'] = CashdeskSession.active.all()
        return ctx


@troubleshooter_user_required
def transaction_reprint(request: HttpRequest, pk: int) -> HttpResponseRedirect:
    if request.method == 'POST':
        try:
            transaction = Transaction.objects.get(pk=pk)
        except Transaction.DoesNotExist:
            messages.error(request, _('Unknown transaction.'))
        else:
            transaction.print_receipt(do_open_drawer=False)
            messages.success(request, _('Receipt has been reprinted at {}.').format(transaction.session.cashdesk))

    return redirect('troubleshooter:transaction-detail', pk=pk)


@troubleshooter_user_required
def transaction_invoice(request, pk) -> Union[HttpResponse, HttpResponseRedirect]:
    def return_invoice(path: str, pk: int=pk) -> HttpResponse:
        response = HttpResponse(content=default_storage.open(path, 'rb'))
        response['Content-Type'] = 'application/pdf'
        response['Content-Disposition'] = 'inline; filename=invoice-{}.pdf'.format(pk)
        return response

    try:
        transaction = Transaction.objects.get(pk=pk)
    except Transaction.DoesNotExist:
        messages.error(request, _('Unknwon transaction.'))
        return redirect('troubleshooter:transaction-list')

    path = transaction.get_invoice_path()
    if path:
        return return_invoice(path)

    form = InvoiceAddressForm()
    if request.method == 'POST':
        form = InvoiceAddressForm(request.POST)
        if form.is_valid():
            path = generate_invoice(transaction, form.cleaned_data['address'])
            return return_invoice(path)
        else:
            messages.error(request, str(form.errors))

    return render(request, 'troubleshooter/invoice.html', {'form': form})

src/postix/troubleshooter/views/utils.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin


def troubleshooter_user(user):
    if user.is_authenticated:
        return user.is_troubleshooter
    return False


class TroubleshooterUserRequiredMixin(UserPassesTestMixin):
    login_url = 'troubleshooter:login'

    def test_func(self):
        return troubleshooter_user(self.request.user)


troubleshooter_user_required = user_passes_test(troubleshooter_user, login_url='troubleshooter:login')

src/postix/troubleshooter/templates/troubleshooter/base.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load compress %}

{% block area_stylesheets %}
    {% compress css %}
        <link rel="stylesheet" type="text/css" href="{% static "shared/fonts/fonts.css" %}">
        <link rel="stylesheet" type="text/x-scss" href="{% static "troubleshooter/scss/postix.scss" %}">
    {% endcompress %}
    {% block stylesheets %}
    {% endblock %}
    {% block meta %}
    {% endblock %}
{% endblock %}

{% block area_url %}{% url "troubleshooter:main" %}{% endblock %}
{% block area %}{% trans "Troubleshooter" %}{% endblock %}



{% block area_content %}
    <div class="backoffice-main">
        <h1>{% block headline %}{% endblock %}</h1>
        <div class="backoffice-content">
            <p>
                {% block content %}
                {% endblock %}
            </p>
        </div>
    </div>
{% endblock %}

{% block area_scripts %}
    <script type="text/javascript" src="{% static "troubleshooter/js/requests.js" %}"></script>

    {% block scripts %}
    {% endblock %}
{% endblock %}

src/postix/troubleshooter/templates/troubleshooter/constraint_detail.html
{% extends 'troubleshooter/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
    <div class="alert alert-warning">
        {% if restricted %}
            {% trans "This list is protected. A maximum of 10 results will be shown for any given query." %}
        {% endif %}
    </div>
    <h1>{% trans "Liste" %} {{ constraint }}</h1>
    <strong>{% trans "Products" %}</strong>
    <ul>
        {% for through in constraint.product_constraints.all %}
            <li>
                {{ through.product }}
                {% if through.price %}
                    {% blocktrans trimmed with price=through.price %}
                        (at extra charge of {{ price }} €)
                    {% endblocktrans %}
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <p></p>
    <h2>{% trans "Entries" %}</h2>
    <form class="form form-inline" action="" method="get">
        <p>
            <input type="text" class="form-control" name="filter">
            <button class="btn btn-primary form-control" type="submit">{% trans "Filter" %}</button>
        </p>
    </form>
    <div>
        <ul>
            {% for entry in entries %}
                <li>
                    {{ entry.name }} ({{ entry.identifier }})
                    {% if entry.is_redeemed %}
                        <em>({% trans "redeemed" %})</em>
                    {% endif %}
                </li>
            {% empty %}
                {% trans "No entries found." %}
                {% if restricted %}
                    {% trans "This list is protected. Please submit a query to see entries." %}
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

src/postix/troubleshooter/templates/troubleshooter/constraints_list.html
{% extends 'troubleshooter/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headline %}{% trans "Lists" %}{% endblock %}
{% block content %}

    <ul>
        {% for list_constraint in constraints %}
            <li>
                <a href="{% url "troubleshooter:constraint-detail" pk=list_constraint.pk %}">
                    {{ list_constraint }}
                </a>
                <ul>
                    <li>{% trans "Entries" %}: {{ list_constraint.entries.count }}</li>
                    <li>{% trans "Products" %}:
                        <ul>
                            {% for through in list_constraint.product_constraints.all %}
                                <li>
                                    {{ through.product }}
                                    {% if through.price %}
                                        {% blocktrans trimmed with price=through.price %}
                                            (at extra charge of {{ price }} €)
                                        {% endblocktrans %}
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </li>
        {% empty %}
            {% trans "No list constraints can be displayed at the moment. Please call an administrator if you think this is wrong." %}
        {% endfor %}
    </ul>
{% endblock content %}

src/postix/troubleshooter/templates/troubleshooter/fail.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>postix</title>
    <link rel="stylesheet" type="text/css" href="{% static "shared/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "shared/css/bootstrap-theme.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "shared/fonts/fonts.css" %}">
</head>
<body class="error">
<div class="error-page">
<span class="fa fa-eye-slash"></span>

    <h2>{{ message }}</h2>
    {% if detail %}
        <p>{{ detail }}</p>
    {% endif %}
    {% if offer_logout %}
    <p><a href="{% url "backoffice:logout" %}" class="btn btn-default btn-lg">{% trans "Log out" %}</a></p>
    {% endif %}
</div>
<script type="text/javascript" src="{% static "shared/js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "troubleshooter/js/login.js" %}"></script>
</body>
</html>

src/postix/troubleshooter/templates/troubleshooter/main.html
{% extends 'troubleshooter/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headline %}{% trans "Current sessions" %}{% endblock %}
{% block meta %}
    <meta http-equiv="refresh" content="5">
{% endblock %}
{% block content %}
    <div class="">
        <div class="panel">
            <ul class="list-group">
                {% for sess in sessions %}
                {% with sess.has_open_requests as requests %}
                    <li class="list-group-item open-cashdesk {% if requests %} has-request list-group-item-warning{% endif %}">
                        <h3>
                            <a href="{% url "troubleshooter:transaction-list" %}?desk={{ sess.cashdesk.pk }}">
                                {{ sess.cashdesk }}</a>
                            <small>{% trans "User" %}: {{ sess.user }}</small>
                        </h3>

                        {% if requests %}
                            <span class="badge">
                                <span class="fa fa-exclamation-circle"></span>
                                {% trans "Resupply" %}<br />
                                <form action="{% url "troubleshooter:confirm-resupply" pk=sess.pk %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-xs btn-success" type="submit" style="margin-top: 5px;"href="{% url "troubleshooter:confirm-resupply" pk=sess.pk %}" method="post">
                                        <span class="fa fa-check-circle"></span>
                                    </button>
                                </form>
                            </span>
                        {% endif %}
                        <dl class="dl-horizontal">
                            <dt>{% trans "Session time" %}</dt>
                            <dd>{{ sess.start|timesince }} </dd>
                            {% for i in sess.current_items %}
                                <dt>{{ i.item }}</dt>
                                <dd>{{ i.total }}</dd>
                            {% endfor %}
                        </dl>
                    </li>
                {% endwith %}
                {% empty %}
                    {% trans "This is it: the calm before (or after?) the storm. Hold tight, shifts will appear here shortly." %}
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

src/postix/troubleshooter/templates/troubleshooter/preorder_information.html
{% extends 'troubleshooter/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headline %}{% trans "Preorders" %}
{% endblock %}
{% block content %}

    <div>
    {% blocktrans trimmed %}
        These are preorder positions with special information attached, and their current status.
    {% endblocktrans %}
    <form class="form form-inline pull-right" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary">{% trans "Print list" %}</button>
    </form>
    </div>


    <div class="transaction-list table-responsive col-md-12">
        {% if not positions %}
            {% trans "No matching orders found." %}
        {% else %}
            <table class="table table-condensed table-hover">
                <thead>
                <tr>
                    <th> {% trans "Arrived" %} </th>
                    <th> {% trans "Information" %} </th>
                    <th> {% trans "Order code" %} </th>
                </tr>
                </thead>
                <tbody>
                {% for position in positions %}
                    <tr>
                        <td>
                            {% if position.is_redeemed %}
                                <span class="fa fa-check-circle text-success"></span>
                            {% else %}
                                <span class="fa fa-times-circle text-danger"></span>
                            {% endif %}
                        </td>
                        <td>
                            {{ position.information }}
                        </td>
                        <td class="session-action-column">
                            <a href="{% url "troubleshooter:preorder-detail" pk=position.preorder.pk %}" title="{% trans "Details" %}">
                                {{ position.preorder.order_code }}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>

    {% include "core/pagination.html" %}
{% endblock content %}

src/postix/troubleshooter/templates/troubleshooter/preorders.html
{% extends 'troubleshooter/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headline %}{% trans "Preorders" %}{% endblock %}
{% block content %}

    <div class="transaction-filter-header row">
        <form class="form" action="" method="get">
            <div class="col-md-9">
                <input class="form-control" name="code" placeholder="{% trans "Order code" %}"
                        value="{{ request.GET.code }}">
            </div>
            <div class="col-md-3">
                <button class="btn btn-primary btn-block" type="submit">{% trans "Filter" %}</button>
            </div>
        </form>
    </div>
    <div class="transaction-list table-responsive">
        {% if not preorders %}
            {% trans "No matching orders found." %}
        {% else %}
            <table class="table table-condensed table-hover">
                <thead>
                <tr>
                    <th> {% trans "Order code" %} </th>
                    <th> {% trans "Paid" %} </th>
                </tr>
                </thead>
                <tbody>
                {% for p in preorders %}
                    <tr>
                    <td class="session-action-column">
                        <a href="{% url "troubleshooter:preorder-detail" pk=p.pk %}" title="{% trans "Details" %}">
                            {{ p.order_code }}
                        </a>
                    </td>
                    <td>
                        {% if p.is_paid %}{% trans "Yes" %}{% else %}{% trans "No" %}{% endif %}
                    </td>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>

    {% include "core/pagination.html" %}
{% endblock content %}

src/postix/troubleshooter/templates/troubleshooter/transaction_detail.html
{% extends 'troubleshooter/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headline %}{% trans "Transaction" %} #{{ transaction.pk }} ({{ transaction.session.cashdesk }}){% endblock %}

{% block content %}
<div>
    <h3>{{ transaction.session.user }}, {{ transaction.datetime|date:"Y-m-d H:i" }}</h3>
</div>
{% if transaction.receipt_id %}
<p>{% trans "Receipt ID" %}: {{ transaction.receipt_id }}</p>
{% endif %}

{% if transaction.receipt_id %}
    <div class="row">
        <form class="form form-inline col-md-9" method="post" action="{% url "troubleshooter:transaction-reprint" pk=transaction.pk %}">
            {% csrf_token %}
            <select name="session" class="form-control">
                {% for session in sessions %}
                    <option value="{{ session.pk }}">
                    {{ session.user }} {% trans "at" %} {{ session.cashdesk }}
                    </option>
                {% endfor %}
            </select>
            <button class="btn btn-primary" type="submit">{% trans "Print receipt" %}</button>
        </form>
        <form class="form form-inline col-md-3" method="post" action="{% url "troubleshooter:transaction-invoice" pk=transaction.pk %}">
            {% csrf_token %}
            <div class="input group">
            <button class="btn btn-default btn-block" type="submit">{% trans "Print invoice" %}</button>
            </div>
        </form>
    </div>
{% endif %}
<p></p>
<div class="table-responsive">
    <table class="table table-condensed table-hover">
        <tbody>
            {% for position in transaction.positions.all %}
                <tr>
                    <td>
                        {% if position.was_reversed %}
                            <a href="{% url "troubleshooter:transaction-detail" pk=position.reversed_by.all.0.transaction.pk %}">
                                <span class="text-danger">[{% trans "canceled" %}]</span>
                            </a>
                        {% else %}
                            {% if position.type == 'reverse' %}
                                <a href="{% url "troubleshooter:transaction-detail" pk=position.reverses.transaction.pk %}">
                                    <span class="text-danger">{% trans "cancelation" %}</span>
                                </a>
                            {% endif %}
                        {% endif %}
                    </td>
                    <td> {{ position.product }} </td>
                    <td> {{ position.value }} </td>
				</tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}